"""Tabelas Nova23428561652654156541

Revision ID: 3201ad4107b2
Revises: 
Create Date: 2026-02-07 03:34:25.247934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3201ad4107b2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('servicos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('modalidade', sa.String(), nullable=True),
    sa.Column('duracao', sa.Interval(), nullable=True),
    sa.Column('preco', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_servicos_id'), 'servicos', ['id'], unique=False)
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('senha', sa.String(), nullable=True),
    sa.Column('admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_usuarios_id'), 'usuarios', ['id'], unique=False)
    op.create_table('agendamentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('nome_completo', sa.String(), nullable=True),
    sa.Column('servico_id', sa.Integer(), nullable=True),
    sa.Column('hora_comeco', sa.Time(), nullable=True),
    sa.Column('hora_fim', sa.Time(), nullable=True),
    sa.Column('dia', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('pendente', 'confirmado', 'cancelado'), nullable=True),
    sa.ForeignKeyConstraint(['servico_id'], ['servicos.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agendamentos_id'), 'agendamentos', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_agendamentos_id'), table_name='agendamentos')
    op.drop_table('agendamentos')
    op.drop_index(op.f('ix_usuarios_id'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_servicos_id'), table_name='servicos')
    op.drop_table('servicos')
    # ### end Alembic commands ###
